# Generated by Django 2.0.3 on 2020-08-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Item'),
            preserve_default=False,
        ),
    ]
