# Generated by Django 2.0.3 on 2020-08-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_gallery_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='item',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.Item'),
        ),
    ]
