# Generated by Django 2.0.3 on 2020-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200814_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image'),
        ),
    ]
