# Generated by Django 2.0.3 on 2020-08-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_carditem_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
    ]
